name: NuGet Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Test with XUnit
      run: dotnet test ./TailwindMerge.Tests/TailwindMerge.Tests.csproj --configuration Release --no-build --verbosity normal
    
    - name: Pack
      run: dotnet pack ./TailwindMerge/TailwindMerge.csproj --configuration Release --no-build -o ./nupkg
    
    - name: Push to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
